language: php
php:
  - 5.6
env:
  - MAGE=1.9.1.0
before_script:
  - MAGE_DIR=build
  # Install mage-ci
  - source <(curl -s https://raw.githubusercontent.com/EcomDev/MageCI/master/installer)
  # Installing magento version with prepared DB dump
  - bin/mage-ci install $MAGE_DIR $MAGE magento -c
  # Copy composer.json for a build (without magento dependency)
  - cp .travis/composer.json ./composer.json
  - rm composer.lock
  # Update composer
  - composer self-update
  # Installing dependencies
  - composer install
  # Installing main module into Magento module
  - bin/mage-ci install-module $MAGE_DIR $(pwd)
  # Enable
  - cp .travis/EcomDev_LayoutCompilerTestEnabler.xml build/app/etc/modules/
  - cp .travis/phpunit.xml build/
  - mkdir -p build/var/phpunit/cov
script:
  - bin/phpunit -c phpunit.xml --colors --coverage-php=build/var/phpunit/cov/01-unit.cov
after_script:
  - bin/phpcov merge build/var/phpunit/cov --clover build/var/phpunit/coverage.xml
  - bin/coveralls -v