language: php
php:
  - 5.6
env:
  - MAGE=1.9.1.0
before_script:
  - MAGE_DIR=src
  - composer self-update
  - composer install -dev
  - bin/mage-ci install $MAGE_DIR $MAGE magento -c
script:
  - bin/phpunit -c phpunit.xml
